### DISCUSSION TITLE
API Agent

### DISCUSSION THREAD

**Discussion by IamTaoChen** [lejianwen/rustdesk-api#129] [Ideas]
我正在查看RustDesk支持的cli，https://github.com/rustdesk/rustdesk/discussions/3980#discussioncomment-11172341

我在想是否可以创建一个Agent来设置Rustdesk的配置，这样API可以控制客户端。Agent通过cli来设置和更新rustdesk，同时Agent通过Token或者手动加入API Server. 

当然也有一定的风险，如果API server被别人控制了，所有使用agent的设备都会被别人控制

**Comment by IamTaoChen** [comment]
也可以修改配置文件`C:\Users\%USERNAME%\AppData\Roaming\RustDesk\config\RustDesk2.toml`
```toml
rendezvous_server = 'XXXXX:21116'
nat_type = 1
serial = 0
unlock_pin = ''
trusted_devices = ''

[options]
allow-remove-wallpaper = 'Y'
allow-remote-config-modification = 'Y'
key = '==XXXX'
av1-test = 'N'
relay-server = 'XXXX'
direct-server = 'Y'
local-ip-addr = 'XXXX'
api-server = 'https://XXXXX.com'

```
