### DISCUSSION TITLE
Running server integrated with api and mysql

### DISCUSSION THREAD

**Discussion by Karol347** [lejianwen/rustdesk-api#197] [General]
HI 
I have problem with running complete rustdesk server with api, must login option and mysql on my host.
Any solution or prefered complete docker stack?

**Comment by lejianwen** [comment]
```
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RELAY=<server[:21117]>
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=Y
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=<server[:21116]> #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<server[:21117]> #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://<server[:21114]> #21114
       - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
       - RUSTDESK_API_JWT_KEY=xxxxxx # jwt key
       - RUSTDESK_API_GORM_TYPE=mysql
       - RUSTDESK_API_MYSQL_USERNAME=<mysql_username>
       - RUSTDESK_API_MYSQL_PASSWORD=<mysql_pwd>
       - RUSTDESK_API_MYSQL_ADDR=<mysql_addr>  #eg: 127.0.0.1:3306
       - RUSTDESK_API_MYSQL_DBNAME=<mysql_dbname>
     volumes:
       - /data/rustdesk/server:/data  #将server的key挂载出来
       - /data/rustdesk/api:/app/data #将数据库挂载
     networks:
       - rustdesk-net
     restart: unless-stopped
  mysql:
    ...
```

**Comment by Karol347** [comment]
This setup generates sqllite and pub and priv key?
Can i use own keys?
Becouse it dont works :(

**Comment by lejianwen** [comment]
When using `RUSTDESK_API_GORM_TYPE=mysql`, sqlite will not be used
`pub and priv key` can be mounted . `<your data>:/data`

Reference：
https://github.com/rustdesk/rustdesk-server?tab=readme-ov-file#s6-overlay-based-images

**Comment by Karol347** [comment]
I tan be mounted by folder or adding variables?

ENCRYPTED_ONLY | yes | if set to "1" unencrypted connection will not be accepted
KEY_PUB | yes | public part of the key pair
KEY_PRIV | yes | private part of the key pair

Can you show example compose with keys?

**Reply by lejianwen** [reply]
```
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RELAY=<server[:21117]>
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=Y
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=<server[:21116]> #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<server[:21117]> #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://<server[:21114]> #21114
       - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
       - RUSTDESK_API_JWT_KEY=xxxxxx # jwt key
       - RUSTDESK_API_GORM_TYPE=mysql
       - RUSTDESK_API_MYSQL_USERNAME=<mysql_username>
       - RUSTDESK_API_MYSQL_PASSWORD=<mysql_pwd>
       - RUSTDESK_API_MYSQL_ADDR=<mysql_addr>  #eg: 127.0.0.1:3306
       - RUSTDESK_API_MYSQL_DBNAME=<mysql_dbname>
       - KEY_PUB=<your pub key>
       - KEY_PRIV=<your priv key>
     volumes:
       - /data/rustdesk/server:/data  #将server的key挂载出来
       - /data/rustdesk/api:/app/data #将数据库挂载
     networks:
       - rustdesk-net
     restart: unless-stopped
  mysql:
    ...
```
