### DISCUSSION TITLE
有几个疑问 还烦请有空回答

### DISCUSSION THREAD

**Discussion by pope-L** [lejianwen/rustdesk-api#297] [Q&A] [answered]
jwttoken 那个 只与apiserver 有关系吧， 不用放在hbbr、s 的工作目录中。env中吧？
apiserver 的config.yaml 文件中 是填写 自己的实际地址吧？
```
rustdesk:
  id-server: "172.16.99.119:21116"
  relay-server: "172.16.99.119:21117"
  api-server: "http://172.16.99.119:21114"
  key: ""
  key-file: "/var/lib/rustdesk-server/id_ed25519.pub"
  personal: 1
```
key 后面是要填写id_ed25519文件里的内容嘛 还是为空？
keyfile 后面我指向rustdeskserver的 目录中文件 可以嘛？
这里的个人或者否 是什么意思的呢？
开启了mustlogin=Y 是否只是 限制了 登录了的机子才可以远程别人， 但被控的机子不受此限制？

通过webclient 连接 其他机子 显示key不匹配 但 手机端或者电脑端可以正常连的？

```
附rustdeskserver下的 .env
ENCRYPTED_ONLY=1
MUST_LOGIN=Y
ALWAYS_USE_RELAY=N
DB_URL= qlite://./db_v2.sqlite3
DOWNGRADE_START_CHECK=60
#DOWNGRADE_THRESHOLD=0.66
#KEY
LIMIT_SPEED=10
#PORT
#RELAY_SERVERS
RUST_LOG=warn
#all           debug level (error|warn|info|debug|trace)
#SINGLE_BANDWIDTH
#TOTAL_BANDWIDTH
```
