### DISCUSSION TITLE
Allow connection to Remoteclient only when logged in

### DISCUSSION THREAD

**Discussion by danigl93** [lejianwen/rustdesk-api#79] [Ideas]
Hello,
is it possible to implement a feature that allows connections to the remote client only when the user is logged in (API)

Best regards

**Comment by lejianwen** [comment]
This must be supported by the server 
You can try this https://github.com/sctg-development/sctgdesk-server

**Reply by GusevVictor** [reply]
> This must be supported by the server You can try this https://github.com/sctg-development/sctgdesk-server

Can I use your implementation of api with that server? That api implementation has a lot of bugs.

**Reply by lejianwen** [reply]
You can try
And you can try https://github.com/lejianwen/rustdesk-server

**Reply by GusevVictor** [reply]
> You can try And you can try https://github.com/lejianwen/rustdesk-server

I don't understand how to use hbbs from that repo with your api implementation. Could you give me some examples, please? I need to avoid connecting logged-off users

**Reply by lejianwen** [reply]
> I don't understand how to use hbbs from that repo with your api implementation. Could you give me some examples, please? I need to avoid connecting logged-off users

Make a backup before you do so

- May be just use it like you would use the official one, if  https://github.com/sctg-development/sctgdesk-server

```
  networks:
    rustdesk-net:
      external: false
  services:
    hbbs:
      container_name: hbbs
      ports:
        - 21115:21115
        - 21116:21116
        - 21116:21116/udp
        - 21118:21118
      image: sctg/sctgdesk-server
      command: hbbs -r <server[:21117]> -k <key>
      volumes:
        - /data/rustdesk/server:/root
      networks:
        - rustdesk-net
      depends_on:
        - hbbr
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 64M
    hbbr:
      container_name: hbbr
      ports:
        - 21117:21117 # 自定义 hbbr 映射端口
        - 21119:21119 # web client
      image: sctg/sctgdesk-server
      command: hbbr -k <key>
      volumes:
        - /data/rustdesk/server:/root
      networks:
        - rustdesk-net
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 64M
    rustdesk-api:
      container_name: rustdesk-api
      environment:
        - TZ=Asia/Shanghai
        - RUSTDESK_API_RUSTDESK_ID_SERVER=<server[:21116]>
        - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<server[:21117]>
        - RUSTDESK_API_RUSTDESK_API_SERVER=http://<server[:21114]>
        #- RUSTDESK_API_RUSTDESK_KEY=<key>
      ports:
        - 21114:21114
      image: lejianwen/rustdesk-api
      volumes:
        - /data/rustdesk/api:/app/data #将数据库挂载出来方便备份
        - /data/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
      networks:
        - rustdesk-net
      restart: unless-stopped
      depends_on:
        - hbbs
        - hbbr
```

- if https://github.com/lejianwen/rustdesk-server , use [lejianwen/rustdesk-server-s6](https://hub.docker.com/r/lejianwen/rustdesk-server-s6)

```
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RELAY=<relay_server[:port]>
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=N
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=<id_server[:21116]>
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<relay_server[:21117]>
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://<api_server[:21114]>
       - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
       - RUSTDESK_API_JWT_KEY=xxxxxx # jwt key
     volumes:
       - /data/rustdesk/server:/data
       - /data/rustdesk/api:/app/data 
     networks:
       - rustdesk-net
     restart: unless-stopped
       
```
