### DISCUSSION TITLE
使用lucky开启HTTPS反向代理和webclient2连接

### DISCUSSION THREAD

**Discussion by rayangl** [lejianwen/rustdesk-api#81] [Show and tell]
### 说明

1. 我的网络环境是双栈动态公网，没有443端口；[lucky](https://github.com/gdy666/lucky)的安装以及配置ddns和ssl略过，[官网](https://lucky666.cn/docs/modules/web)有对应教程。
2. 我这里只是反代了api：`21114（api的网页后台）和 21118、21119（api网页后台发起远程的WebSocket 端口）`，`21115-21117（客户端发起远程的端口）`均使用openwrt的通信规则放行端口，这些端口应该不适合反代，想反代可以自行尝试。
3. 提供两种Docker部署方式：**S6三镜像合一（推荐）**、官方server+api 避免混淆，教程放最后。
>[!note] 
如果你IPV6有443，IPV4没有443，两者混用时（21114网页后台用有443端口的v6，21118、21119用443以外端口的v4，或者反过来），要打开lucky里面api子规则的跨域选项。
    解释一下混用的场景：https默认走443端口，所以访问不会显示难看的端口。接下来我们部署的web网页你就可以选择用v4还是v6，如果你全用v6，虽然不会显示端口，但会导致只有v4的人无法打开web网页和发起远程。家宽v4是没有443的，所以必须用端口访问，虽然有其他方法，可以自行搜索。
    电信手机流量因为默认是双栈，可以打开web网页，比如公司默认只有IPV4协议栈，就打不开网站。api服务环境变量：`- RUSTDESK_API_RUSTDESK_API_SERVER`ipv6和ipv4只能写一种地址，如果该环境变量写的v6地址，实际访问使用443以外的端口，就会报错，所以要开启跨域。可以自己研究一下。建议先把IPv4弄好了再来尝试这个东西。
```
       - RUSTDESK_API_RUSTDESK_ID_SERVER=id.做好ddns的域名
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=relay.做好ddns的域名
       - RUSTDESK_API_RUSTDESK_API_SERVER=https://api.做好ddns的域名:反代的端口 例如1999
       - RUSTDESK_API_RUSTDESK_WS_HOST=wss://wss.域名.com:1999
```
![Screenshot_2025-03-24-16-56-44-091_com microsoft emmx](https://github.com/user-attachments/assets/09dc8bac-342f-4e51-8268-1d5ef55096bc)
---
### 一、放行端口
通信规则放行`21115-21117`,其它选项保持默认就行。api网页端口 `21114`和网页远程的端口`21118-21119`我们通过反代的方式，就不需要开放端口了。

- `hbbs`:
  - `21114` (TCP): 用于api网页控制台。
  - `21115` (TCP): 用于 NAT 类型测试。
  - `21116` (TCP/UDP): 请注意 `21116` 应该同时为 TCP 和 UDP 启用。 `21116/UDP` 用于 ID 注册和心跳服务。`21116/TCP` 用于 TCP 打洞和连接服务。
  - `21118` (TCP): 用于Web 客户端的ID支持 WebSocket 端口。
- `hbbr`:
  - `21117` (TCP): 用于中继服务。
  - `21119` (TCP): 用于Web 客户端的中继支持 WebSocket 端口。

![image](https://github.com/user-attachments/assets/174c6645-2519-4e39-b196-2fda8d960dfb)
![image](https://github.com/user-attachments/assets/1778195d-43b5-4a8b-a817-b13d4f376e65)

### 二、使用S6镜像

1. 推荐使用lejianwen/server-s6镜像，普通镜像要运行三个容器，S6一个就行；S6已解决链接超时问题（顺带还解决了红色未加密链接，现在是绿色盾牌了），还可以强制登录后才能发起链接。
<img width="389" height="158" alt="image" src="https://github.com/user-attachments/assets/752b6fc8-3653-4db2-a8c0-b8caa7f0cb3a" />

2.S6镜像compose，更改里面中文的部分为自己的，删除不需要的环境变量和后面注释，如果不更换端口，推荐使用 network_mode: host 模式， 这样 P2P 直连功能才可以使用。
```
version: '3'

services:
   rustdesk:
     network_mode: host
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RELAY=做好ddns的域名:21117
       - ENCRYPTED_ONLY=1 #不接受未加密的连接
       # - MUST_LOGIN=N #是否必须登录，可以配合RUSTDESK_API_JWT_KEY，设置后会通过JWT校验token的合法性
       # - RUSTDESK_API_JWT_KEY=xxxxxx #自定义JWT KEY,为空则不启用JWT，如果没使用上面MUST_LOGIN，建议设置为空
       # - RUSTDESK_API_JWT_EXPIRE_DURATION=168h #JWT有效时间 如果没使用JWT，就删除这几个相关的变量，就使用APP_TOKEN变量就行
       - TZ=Asia/Shanghai
       - RUSTDESK_API_ADMIN_TITLE=RustDesk 控制台
       - RUSTDESK_API_RUSTDESK_ID_SERVER=做好ddns的域名:21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=做好ddns的域名:21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=https://做好ddns的域名:反代的端口 例如1999
       - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub #自动生成key，可以在Docker容器日志查找，然后填写到客户端使用
       - RUSTDESK_API_APP_TOKEN_EXPIRE=8787h #客户端账号登陆过期时间，默认是七天未使用就登出账号，默认只支持h,m,s
       
     volumes:
       - /data/rustdesk/server:/data
       - /data/rustdesk/api:/app/data
       - /tmp/log/rustdeskapi:/app/runtime/ #挂载日志文件，配合fail2ban开启登录防护
     restart: unless-stopped
```
### 三、S6镜像配置lucky
<img width="161" height="258" alt="image" src="https://github.com/user-attachments/assets/362700e5-535f-4b56-9a96-1da2456b2bde" />

前面两步略过，开始第三步，先创建一个web反向代理服务 **(要开启TLS)**，监听你自定义的端口，例如【1999】，再添加三个rustdesk子规则，**默认规则不用动，默认开关不用动**。

#### ① 创建反向代理服务（主规则）
<img width="1117" height="636" alt="image" src="https://github.com/user-attachments/assets/42a7db3f-e0e4-42f2-bab3-3af79426d4da" />

#### ② 创建反向代理服务（默认规则）
<img width="559" height="581" alt="image" src="https://github.com/user-attachments/assets/5c19fbfe-a330-4ff5-9903-02fa5a2ca89a" />

#### ③ 创建反向代理服务（子规则）
<img width="1001" height="801" alt="Screenshot_2026-01-22-09-40-12-348_com microsoft emmx-edit" src="https://github.com/user-attachments/assets/174b7630-8127-4420-ad6c-e4a590f4e42c" />

##### 1. 总览，一共三个
![image](https://github.com/user-attachments/assets/8132ad9f-d2f9-4b87-90e5-92892ad11e55)

##### 2. 创建反代api管理后台（子规则一个）
比如访问前端地址：api.域名.com:1999 反向代理到后端地址 10.10.10.1:21114
![Screenshot_2025-03-20-09-19-08-140_com microsoft emmx](https://github.com/user-attachments/assets/aeaf482f-e1db-45b5-9627-c2c314a82434)

##### 3.创建反代Websocket （WSS）（子规则两个）

> 默认使用api的地址，也就是：【api.域名.com:21118/ws/id】和【api.域名.com:21119/ws/relay】。如果想自定义这个wss地址，比如：wss.域名.com ；那你需要在compose添加一个变量`- RUSTDESK_API_RUSTDESK_WS_HOST=wss://wss.域名.com:1999`，然后在lucky更改成这个反代地址。

```
- RUSTDESK_API_RUSTDESK_WS_HOST=wss://wss.域名.net:1999
```
![image](https://github.com/user-attachments/assets/c8e4752b-9d93-4851-9cff-753d6e59651b)

两个WSS子规则前端域名这里要写上路径，跟后端一样，其他开关保持默认。
![image](https://github.com/user-attachments/assets/0d41ab97-a5e4-4773-b4a4-f660688d100b)

#### 总览
上面我们已经成功创建了一个监听`1999`的主规则和里面的三个子规则，现在再创建一个web重定向服务（主规则）**(不开启TLS)** 和里面的默认规则，用做http跳转https，监听上面你自定义的端口`1999`，填写Lucky变量。重点已框选出来。[lucky官方HTTP跳转HTTPS教程](https://lucky666.cn/docs/modules/web#http%E8%B7%B3%E8%BD%AChttps)

最后的效果就是两个主规则，例如：
##### 1. ipv6
<img width="795" height="139" alt="image" src="https://github.com/user-attachments/assets/b90ee4bc-271d-4cfb-8d5f-986c7092b964" />

##### 2. ipv4 需要改成圈出来的地方
<img width="817" height="78" alt="image" src="https://github.com/user-attachments/assets/b233cc20-6d9f-474d-be01-7645663a5bbc" />

<img width="1116" height="723" alt="image" src="https://github.com/user-attachments/assets/14f0d5a9-1293-4b5d-af9f-583b92f9320d" />

![image](https://github.com/user-attachments/assets/2745dabb-e356-4c04-b30b-ce53ea083ba7)

### 五、客户端配置

使用S6镜像id服务和中继服务并且没有更改默认端口就不用填端口，默认就是21116-21117，api使用了443的不用填，如果是1999这种自定义端口就要填；然后填写docker容器日志里面的密钥就可以开始使用了。普通镜像，在客户端填写的网址一定要加上端口，教程结束。

![image](https://github.com/user-attachments/assets/cfec955a-1373-477c-93d9-c2c1a1d9c101)

#### 1. 部署完了，有两个web服务：
1. apiWEB管理服务：访问https://做好ddns的域名:反代端口1999 能管理用户，发起网页远程。
2. 网页远程服务 访问https://做好ddns的域名:反代端口1999/webclient2 ，出现下面图片这个网页界面就可以了，在地址簿登陆账号会自动同步密钥和服务器地址

#### 2. 一个客户端服务：
ID和relay，前面放行了端口，现在在客户端添入ddns的域名就行。
![Screenshot_2025-03-19-14-14-02-703_com microsoft emmx](https://github.com/user-attachments/assets/4b62544d-b9fc-41f0-b378-4327a4efcb61)

---
### 使用普通镜像

1. `21108:21118` `21109:21119`使用了Docker端口映射。意思是将容器的21118映射到21108。这里如果不改，lucky会无法监听21118，会提示被占用，因为容器监听了这两个，lucky就监听不到了，S6镜像没有这个问题。
> 逻辑是浏览器访问 https://域名.com:端口/webclient2 会请求21118-21119，然后 lucky监听这两个端口，将其转发到21108-21109，Docker再将21108-21109转发到hbbs和hbbr的21118-21119。

2. 普通镜像compose，更改里面中文的部分，为自己的。（不建议使用）
```
version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21108:21118 #/ws/id 网页websocket服务
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r 做好ddns的域名:21117 -k 自定义密钥
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21109:21119 #/ws/relay网页websocket服务
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k 自定义密钥
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

  rustdesk-api:
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_ADMIN_TITLE=RustDesk 控制台
      - RUSTDESK_API_LANG=zh-CN
      - RUSTDESK_API_RUSTDESK_ID_SERVER=做好ddns的域名:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=做好ddns的域名:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=https://做好ddns的域名:反代的端口 例如1999
      - RUSTDESK_API_RUSTDESK_KEY=密钥
    network_mode: host
    image: lejianwen/rustdesk-api:latest
    volumes:
      - /data/rustdesk/api:/app/data#自定义数据要映射的位置
      - /tmp/log/rustdeskapi:/app/runtime/#添加登录日志，方便通过fail2ban封禁异常登录
    restart: unless-stopped
```

---
### 普通镜像配置lucky
普通镜像lucky要多创建两个web服务来监听21118和21119，S6镜像不用，一个端口就可以使用"api"，"/ws/relay"，"/ws/id"了
![image](https://github.com/user-attachments/assets/fb606a0d-97e8-431e-8d58-f7a82367418d)

所以新增两个web服务，监听21108和21109，再分别创建两个子规则，其他选项开关啥的默认即可。
![image](https://github.com/user-attachments/assets/43f5a2c0-3c49-456f-851f-3860937c4747)
![image](https://github.com/user-attachments/assets/137bf952-4131-4b81-8bd6-12958af5f758)
添加两个反代子规则
前端地址：做好ddns的域名，
21118后端地址：http://10.10.10.1:21108/ws/id
21119后端地址：http://10.10.10.1:21109/ws/relay
![image](https://github.com/user-attachments/assets/6324d189-dc81-49be-a866-7786b2f5591c)
访问https://做好ddns的域名:1999/webclient2 就能进入后台了。登录账号应该会自动填写服务器和密钥。
![image](https://github.com/user-attachments/assets/ce00dd3e-0a90-46e1-b10c-0a4fcdcf7c73)
![image](https://github.com/user-attachments/assets/0e0faf22-e70e-4d78-9613-92d38b5fd08f)

#### 1.前面我们映射了log目录，然后openwrt安装fali2ban。
`- /tmp/log/rustdeskapi:/app/runtime/#添加登录日志，方便通过fail2ban封禁异常登录`
![image](https://github.com/user-attachments/assets/e90c0353-12c9-4174-badf-7655364ecfa8)
![image](https://github.com/user-attachments/assets/ae9f6c2a-679f-41ff-a451-138dd00178d0)

#### 2.创建登录失败过滤器

```
vim /etc/fail2ban/filter.d/vaultwarden.conf
```

```bash
[Definition]
failregex = ^.*\[WARN\] Login Fail: UsernameOrPasswordError \d+\.\d+\.\d+\.\d+ <HOST> .*$
ignoreregex =
```

#### 3. 创建监狱规则 
 创建 fail 2 ban 规则目录 (默认不存在)
```
mkdir /etc/fail2ban/jail.d/
```
- 编辑规则
```
vim /etc/fail2ban/jail.d/rustdesk.conf
```
- 填入规则
```INI
[rustdesk]
enabled = true
filter = rustdesk
port = 80,443,21114,1999#填写你的自定义端口
banaction = %(banaction_allports)s
logpath = /tmp/log/rustdeskapi/log.txt
maxretry = 3
findtime = 14400
bantime = 86400
```

>[!note]
>- `Maxretry` =就是密码错误次数错误次数达到这个就封禁这个 IP
>- `Bantime` = 设置被封锁的时间间隔，如下表示 10 分钟，可以是秒 (s)、分钟 (m)、小时 (h)、天 (d)，不带单位则默认为 s，-1 表示永久封锁。
>- `Findtime`  = 14400（4 小时） 检测的间隔时间，在间隔时间内，达到最大尝试次数 `maxretry` 设置的失败次数，则触发限制，禁止访问。 
>- `Logpath` = 具体的日志文件路径 

#### 4. 重启 `fail2ban`
```bash
fail2ban-client restart
```

#### 5. 查看 `fail2ban` 状态
```bash
fail2ban-client status
```

#### 6. 查看登录错误次数以及封禁
```bash
fail2ban-client status rustdesk
```

#### 7. 解除指定封禁
```bash
fail2ban-client unban 192.168.1.16
```

#### 8. 解除所有封禁
```
fail2ban-client unban --all
