### ISSUE TITLE
web client超时连接

### ISSUE THREAD

**Issue by Roxanne299** [lejianwen/rustdesk-api#111]
使用的构建的官方S6镜像部署,其中已经包含了API [Use-Docker-With-Full-S6](https://github.com/lejianwen/rustdesk-api/wiki/Use-Docker-With-Full-S6)

在webclient登录状态连接显示连接超时：
![](https://cdn.jsdelivr.net/gh/Roxanne299/PictureBed//blog/202501211431247.png)
取消连接之后显示：
![](https://cdn.jsdelivr.net/gh/Roxanne299/PictureBed//blog/202501211432554.png)

**Comment by Roxanne299** [comment]
我的compose：
```yml
networks:
   rustdesk-net:
     external: false
 services:
   rustdesk-server:
     container_name: rustdesk-server
     ports:
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: rustdesk/rustdesk-server-s6:latest
     environment:
       - RELAY=[ip]:21117
       - ENCRYPTED_ONLY=1
     volumes:
       - /data/rustdesk/server:/data
     restart: unless-stopped
   rustdesk-api:
     container_name: rustdesk-api
     ports:
       - 21114:21114
     image: lejianwen/rustdesk-api
     environment:
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=[ip]:21116 #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=[ip]:21117 #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://[ip]:21114 #21114
       - RUSTDESK_API_RUSTDESK_KEY=[my key]
     volumes:
       - /data/rustdesk/api:/app/data #将数据库挂载
       - /data/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
     networks:
       - rustdesk-net
     restart: unless-stopped
     depends_on:
       - rustdesk-server

```
