### ISSUE TITLE
https配合nginx动态代理导致web client不能连接问题

### ISSUE THREAD

**Issue by Roxanne299** [lejianwen/rustdesk-api#112]
配置如下：

rustdesk.domain.cn --dns解析->  我的机器ip

**nginx**
```
server {
    server_name rustdesk.domain.cn;
    listen 443 ssl;
    ssl_certificate /etc/nginx/certificate.crt;
    ssl_certificate_key /etc/nginx/private.key;
    location / {
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://ip:21114;
    }

    location /ws/id {
        proxy_pass http://ip:21118;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws/relay {
        proxy_pass http://ip:21119;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

```

**docker-compose.yml**
```yml
networks:
   rustdesk-net:
     external: false
 services:
   rustdesk-server:
     container_name: rustdesk-server
     ports:
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: rustdesk/rustdesk-server-s6:latest
     environment:
       - RELAY=ip:21117
       - ENCRYPTED_ONLY=1
     volumes:
       - /data/rustdesk/server:/data
     restart: unless-stopped
   rustdesk-api:
     container_name: rustdesk-api
     ports:
       - 21114:21114
     image: lejianwen/rustdesk-api
     environment:
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=ip #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=ip #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=https://rustdesk.domain.cn #21114
       - RUSTDESK_API_RUSTDESK_KEY=key
     volumes:
       - /data/rustdesk/api:/app/data #将数据库挂载
       - /data/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
     networks:
       - rustdesk-net
     restart: unless-stopped
     depends_on:
       - rustdesk-server

```

上述配置再webclient
![](https://cdn.jsdelivr.net/gh/Roxanne299/PictureBed//blog/202501222234974.png)

最后报错
![](https://cdn.jsdelivr.net/gh/Roxanne299/PictureBed//blog/202501222236592.png)

**Comment by Roxanne299** [comment]
把
```
- RUSTDESK_API_RUSTDESK_ID_SERVER=ip #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=ip #21117
```
修改成：
```
- RUSTDESK_API_RUSTDESK_ID_SERVER=ip：21116 #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=ip：21117 #21117
```
报错变成了
![](https://cdn.jsdelivr.net/gh/Roxanne299/PictureBed//blog/202501222249899.png)

**Comment by lejianwen** [comment]
这里IP要改为域名
```
- RUSTDESK_API_RUSTDESK_ID_SERVER=ip：21116 #21116
- RUSTDESK_API_RUSTDESK_RELAY_SERVER=ip：21117 #21117
 ```
参考 https://github.com/lejianwen/rustdesk-api/wiki/HTTPS-Reverse-Proxy

**Comment by Roxanne299** [comment]
- RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk.domain.cn:21116 #21116
- RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk.domain.cn:21117 #21117
这个配置显示连接超时

- RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk.domain.cn #21116
- RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk.domain.cn #21117
这个现实不带端口的连接错误

**Comment by lejianwen** [comment]
Web端和被控端里面的配置都只填域名，不带端口号

**Comment by Roxanne299** [comment]
还是超时

**Comment by Roxanne299** [comment]
被控端如果id栏填域名 会连不上 id栏填ip会就绪

**Comment by lejianwen** [comment]
> 被控端如果id栏填域名 会连不上 id栏填ip会就绪

为什么会连不上呢？

**Comment by lejianwen** [comment]
Dns解析没生效？

**Comment by Roxanne299** [comment]
**docker-compose**
```yml
networks:
   rustdesk-net:
     external: false
 services:
   rustdesk-server:
     container_name: rustdesk-server
     ports:
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: rustdesk/rustdesk-server-s6:latest
     environment:
       - RELAY=restdesk.waaar.cn
       - ENCRYPTED_ONLY=1
     volumes:
       - /data/rustdesk/server:/data
     restart: unless-stopped
   rustdesk-api:
     container_name: rustdesk-api
     ports:
       - 21114:21114
     image: lejianwen/rustdesk-api
     environment:
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk.waaar.cn #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk.waaar.cn #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=https://rustdesk.waaar.cn #21114
       - RUSTDESK_API_RUSTDESK_KEY=3LwCArpA5btC5oELa7CqwmS0GUfOiHMmXcWxq5lwwUM=
     volumes:
       - /data/rustdesk/api:/app/data #将数据库挂载
       - /data/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
     networks:
       - rustdesk-net
     restart: unless-stopped
     depends_on:
       - rustdesk-server

```


**nginx配置没变**

dns解析应该是正常的，访问能够出网址

但是被控端
![](https://cdn.jsdelivr.net/gh/Roxanne299/PictureBed//blog/202501231039984.png)

![Image](https://github.com/user-attachments/assets/5056bad0-e2f2-4373-b305-40f71aaf30e3)
