### ISSUE TITLE
v2.6.6 Cannot log in

### ISSUE THREAD

**Issue by delko-it** [lejianwen/rustdesk-api#113]
Hello, and thank you for a nice piece of good rustdesk api.
Having some trouble on latest release: 
On 2.6.6 when i successfully login and click any menu item, it logs out immediately.
Downgrading to 2.6.5 solves the problem.

**Comment by lejianwen** [comment]
```yaml
app:
    token-expire: 36000

```

Add this configuration into conf.yaml

**Comment by lejianwen** [comment]
Ok, i need time to check it

Thank you report

If i  finished , i will comment here

**Comment by lejianwen** [comment]
I noticed that you mounted `./conf:/app/conf`.
The old `config.yaml` did not have `token-expire`.
Add it to `config.yaml` like this:

```
app:
  web-client: 1  # 1:启用 0:禁用
  register: false #是否开启注册
  show-swagger: 0 # 1:启用 0:禁用
  token-expire: 360000
```

I will give `token-expire` a default value in the next version.
