### ISSUE TITLE
请教一下，我部署三合一的问题

### ISSUE THREAD

**Issue by hexsen929** [lejianwen/rustdesk-api#137]
```
networks:
    rustdesk-net:
      external: false
  services:
    hbbs:
      container_name: hbbs
      ports:
        - 21115:21115
        - 21116:21116
        - 21116:21116/udp
        - 21118:21118
      image: rustdesk/rustdesk-server
      command: hbbs -r <server[:21117]> -k <key>
      volumes:
        - /data/rustdesk/server:/root
      networks:
        - rustdesk-net
      depends_on:
        - hbbr
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 64M
    hbbr:
      container_name: hbbr
      ports:
        - 21117:21117 # 自定义 hbbr 映射端口
        - 21119:21119 # web client
      image: rustdesk/rustdesk-server
      command: hbbr -k <key>
      volumes:
        - /data/rustdesk/server:/root
      networks:
        - rustdesk-net
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 64M
    rustdesk-api:
      container_name: rustdesk-api
      environment:
        - TZ=Asia/Shanghai
        - RUSTDESK_API_RUSTDESK_ID_SERVER=<server[:21116]>
        - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<server[:21117]>
        - RUSTDESK_API_RUSTDESK_API_SERVER=http://<server[:21114]>
        #- RUSTDESK_API_RUSTDESK_KEY=<key>
      ports:
        - 21114:21114
      image: lejianwen/rustdesk-api
      volumes:
        - /data/rustdesk/api:/app/data #将数据库挂载出来方便备份
        - /data/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
      networks:
        - rustdesk-net
      restart: unless-stopped
      depends_on:
        - hbbs
        - hbbr
```

我部署的时候报错：
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: run create failed: unable to start container process: exec: "hbbr -k he94209s": executable file not found in SPATH: unknown
`
