### ISSUE TITLE
Web Client无法连接、p2p打洞失败

### ISSUE THREAD

**Issue by jimmygiven** [lejianwen/rustdesk-api#140]
搜索了一天仍没解决问题，辛苦大佬帮忙看下。

按照大佬的Use Docker With My S6方法构建，nginx在本地运行。api的web除client各项功能正常，设备之间可以进行控制，但一直使用的是中继模式。

想解决以下两个问题：
问题一是WebClient无法连接，提示“Failed to connect to rendezvous server, wss://域名:12318”
问题二是一直使用中继模式，无法使用p2p打洞，即便已经勾选了允许建立tcp隧道。

nginx配置如下：

```
server
    {
        listen 80;
        #listen [::]:80;
        server_name 域名 ;
	return 301 https://$server_name$request_uri;
}

server
    {
        listen 127.0.0.1:50009 ssl proxy_protocol so_keepalive=on;
        # listen [::]:443 ssl http2;
	http2  on;
	port_in_redirect off;
	set_real_ip_from 127.0.0.1;
	real_ip_header proxy_protocol;
        server_name 域名 ;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/域名;

        ssl_certificate /usr/local/nginx/conf/ssl/域名/fullchain.cer;
        ssl_certificate_key /usr/local/nginx/conf/ssl/域名/域名.key;
		
        ssl_certificate /usr/local/nginx/conf/ssl/域名_ecc/fullchain.cer;
        ssl_certificate_key /usr/local/nginx/conf/ssl/域名_ecc/域名.key;
		
	server_tokens off;
		
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_ciphers TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
        ssl_session_cache builtin:1000 shared:SSL:10m;
        ssl_session_timeout 1d;
        # openssl dhparam -out /usr/local/nginx/conf/ssl/dhparam.pem 2048
        ssl_dhparam /usr/local/nginx/conf/ssl/dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	# 0-RTT
	ssl_early_data on;
		
	location / {
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:12314/;
    }

    location /ws/id {
        proxy_pass http://127.0.0.1:12318;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws/relay {
        proxy_pass http://127.0.0.1:12319;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
docker-compose配置如下（一直无法调好换行显示只能截图了，还请谅解）

![Image](https://github.com/user-attachments/assets/d6137374-40a2-46d6-b445-dce0e397adbe)

Web Client错误信息如下：

![Image](https://github.com/user-attachments/assets/56a365a2-47bc-4044-bb05-3974191217c5)

搜到rustdesk作者的说明文档和回复中都提到docker要使用host模式才可以获取ip进行p2p打洞，出于安全和隐私方面的考虑，想更换为不常见端口，大佬可以解答一下能否实现吗

**Comment by lejianwen** [comment]
非常规端口，不用反代目录 ，直接反代端口

**Comment by lejianwen** [comment]
[github.com/lejianwen/rustdesk-api](https://github.com/lejianwen/rustdesk-api/wiki/HTTPS-Reverse-Proxy#https-%E9%9D%9E443%E7%AB%AF%E5%8F%A3-%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)

**Comment by jimmygiven** [comment]
> 非常规端口，不用反代目录 ，直接反代端口

感谢大佬解答，因为nginx在docker之外，目前还是没有头绪，接下来准备尝试一下不用docker全都本地化的方式看看能不能解决问题

**Comment by lejianwen** [comment]
在docker外的话改下端口或者IP就行
假设nginx和docker在同一主机
```
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 127.0.0.1:22318:21118  #注意这里暴露端口修改一下
       - 127.0.0.1:22319:21119   #注意这里暴露端口修改一下
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RELAY=<server[:21117]>
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=Y #是否必须登录
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=<server[:21116]> #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<server[:21117]> #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://<server[:21114]> #21114
       - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
       - RUSTDESK_API_JWT_KEY=xxxxxx # jwt key
     volumes:
       - /data/rustdesk/server:/data  #将server的key挂载出来
       - /data/rustdesk/api:/app/data #将数据库挂载
     networks:
       - rustdesk-net
     restart: unless-stopped

 ```



nginx


```
server {
    server_name <server>;
    listen 50009 ssl;
    ssl_certificate /etc/nginx/ssl/<server>/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/<server>/privkey.pem; 
    location / {
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rustdesk-api:21114/;
    }
}

server {
    listen 12318 ssl; 
    server_name <server>;
    ssl_certificate /etc/nginx/ssl/<server>/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/<server>/privkey.pem; 
    location / {
        proxy_pass http://127.0.0.1:22318;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 12319 ssl;
    server_name <server>;
    ssl_certificate /etc/nginx/ssl/<server>/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/<server>/privkey.pem; 
    location / {
        proxy_pass http://127.0.0.1:22319;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
