### ISSUE TITLE
指定websocket

### ISSUE THREAD

**Issue by yedajiang44** [lejianwen/rustdesk-api#156]
## 背景

由于种种原因我的api与server不同域名，并且分别指向不同的ip，api指向的ip是四层代理，至server地址，但是websocket似乎使用的是`RUSTDESK_API_RUSTDESK_API_SERVER`，因此导致webcliet页面能打开，但是websocket无法连接

domain1指向ip1，ip1的80、443四层代理至ip2的http、https固定端口
domain2指向ip2，ip2对应的http、https端口使用nginx反代至各种容器的http服务（仅限http）
> domain2的作用仅仅是指向ip2，其服务器的nginx并未对域名domain2进行配置

## 需求

我是否需要变更配置？或者是否可以增加选项已单独设置websocket地址

## 配置

api环境变量配置如下
```
        RUSTDESK_API_RUSTDESK_ID_SERVER: domain2:21116
        RUSTDESK_API_RUSTDESK_RELAY_SERVER: domain2:21117
        RUSTDESK_API_RUSTDESK_API_SERVER: https://domain1
```

domain2的nginx配置如下
```
server {
        listen 443 ssl proxy_protocol;
        listen [::]:443 ssl proxy_protocol;
        http2 on;
        server_name domain1;
        ssl_certificate 证书文件;
        ssl_certificate_key 证书文件;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        client_max_body_size 0;
        location / {
                resolver 127.0.0.11;
                proxy_pass http://rustdesk-api:21114;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header REMOTE-HOST $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Range $http_range;
                proxy_set_header If-Range $http_if_range;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_set_header If-Modified-Since $http_if_modified_since;
                proxy_set_header If-None-Match $http_if_none_match;
                proxy_cache_revalidate on;
                proxy_cache_bypass $http_cache_control;
                add_header Last-Modified $upstream_http_last_modified;
                add_header ETag $upstream_http_etag;
        }

        location /ws/id {
                proxy_pass http://rustdesk-hbbs:21118;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /ws/relay {
                proxy_pass http://rustdesk-hbbr:21119;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}
```
docker-compose配置如下

> 所有映射到宿主的端口已全部映射至外网

```
networks:
  rustdesk:
    name: rustdesk
    driver: bridge

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    restart: always
    command: hbbs -k "key" -r domain2:21117
    volumes:
      - ./data/server:/root
    depends_on:
      - hbbr
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    networks:
      - rustdesk

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    restart: always
    command: hbbr -k "key"
    volumes:
      - ./data/server:/root
    networks:
      - rustdesk
    ports:
      - 21117:21117
      - 21119:21119
  api:
      image: lejianwen/rustdesk-api
      container_name: rustdesk-api
      restart: always
      environment:
        TZ: Asia/Shanghai
        RUSTDESK_API_APP_REGISTER: true
        RUSTDESK_API_RUSTDESK_ID_SERVER: domain2:21116
        RUSTDESK_API_RUSTDESK_RELAY_SERVER: domain2:21117
        RUSTDESK_API_RUSTDESK_API_SERVER: https://domain1
        RUSTDESK_API_RUSTDESK_KEY: key
      volumes:
        - ./data/api:/app/data
      depends_on:
        - hbbs
        - hbbr
      networks:
        - rustdesk
```
