### ISSUE TITLE
Web Client 连接客户端时提示：连接超时

### ISSUE THREAD

**Issue by Land-Doc** [lejianwen/rustdesk-api#192]
用windows 客户端软件连接可以正常连接使用，通过 Web Client 连接提示：连接超时
![Image](https://github.com/user-attachments/assets/b503d98b-3ac0-4831-8068-2d1189f739e7)

点确定后会有提示 Failed to connect to rendezvous server
![Image](https://github.com/user-attachments/assets/61786543-fc0b-4499-ad8f-9476708e8d2f)

compose.yaml 文件配置
```
services:
  rustdesk-server-s6:
    container_name: rustdesk-server-s6 
    image: lejianwen/rustdesk-server-s6:latest  # 非官方镜像    
    ports:
      #- 21114:21114  # web界面，用Nginx代理访问
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      #- 21118:21118  # 用Nginx代理访问
      #- 21119:21119  # 用Nginx代理访问
    environment:
      - RELAY=rustdesk-server-s6:21117
      - ENCRYPTED_ONLY=1
      - MUST_LOGIN=N
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk20250327.域名:21116  
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk20250327.域名:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=https://rustdesk20250327.域名:4443 
      #- RUSTDESK_API_RUSTDESK_KEY=<key>
    volumes:
      - ./rustdesk-server-s6:/data  # rustdesk数据目录，包含数据库和证书文件
      - ./rustdesk-server-s6:/app/conf/data  #挂载key文件到api服务使用，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
      - ./rustdesk-api/conf/config.yaml:/app/conf/config.yaml  # 将配置文件挂载进去，替换默认的配置文件
      - ./rustdesk-api:/app/data  #将 rustdeskapi.db 数据库挂载出去，同时将该目录的 conf/config.yaml 配置文件挂载到容器使用
    networks:
      - rustdesk-net
    restart: always
    
  rustdesk-nginx:
    depends_on:
      - rustdesk-server-s6
    container_name: rustdesk-nginx
    image: nginx:latest
    ports:
      - 4443:443
      - 21118:21118
      - 21119:21119
    volumes:
      - ./rustdesk-nginx/conf.d:/etc/nginx/conf.d
    networks:
      - rustdesk-net
    environment:
      - TZ=Asia/Shanghai      
    restart: always

networks:
   rustdesk-net:
     external: false
```

nginx 配置文件 default.conf
```
server {
    listen 443 ssl;
    server_name rustdesk20250327.域名;  # 实际访问的域名地址
    ssl_certificate /etc/nginx/conf.d/域名.pem;  # 证书
    ssl_certificate_key /etc/nginx/conf.d/域名.key; # 私钥
    location / {
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rustdesk-server-s6:21114/;  # 代理到 rustdesk-server-s6 容器的 21114 端口
    }
    location /ws/id {
        proxy_pass http://rustdesk-server-s6:21116;
        # proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    } 
}

server {
    listen 21118 ssl; 
    server_name rustdesk20250327.域名;
    ssl_certificate /etc/nginx/conf.d/域名pem; 
    ssl_certificate_key /etc/nginx/conf.d/域名.key; 
    location / {
        proxy_pass http://rustdesk-server-s6:21118;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 21119 ssl;
    server_name rustdesk20250327.域名;
    ssl_certificate /etc/nginx/conf.d/域名.pem; 
    ssl_certificate_key /etc/nginx/conf.d/域名.key; 
    location / {
        proxy_pass http://rustdesk-server-s6:21119;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}    
```
