### ISSUE TITLE
Web 客户端: 不能正确记忆输入的自建服务器信息.

### ISSUE THREAD

**Issue by YamatoRyou** [lejianwen/rustdesk-api#230]
版本: 2.6.16 (Docker)

API 服务器地址在填入后的当下有效, 但刷新网页后自动恢复为 `http://127.0.0.1:21114`. 在刷新网页前可以登录.
密钥会在一段时间后被清空 (具体什么情况下被清空有待观察).
ID 服务器地址可以正常记忆.

已经在 `/data/conf/config.yaml` 中填入自建的服务器地址.
```
rustdesk:
  id-server: "rustdesk.example.com:21116"
  relay-server: "rustdesk.example.com:21117"
  api-server: "https://rustdesk.example:21114"
  key: ""
  key-file: "/data/id_ed25519.pub"
```
