### ISSUE TITLE
怎么修改 S6 Docker里面的key ?

### ISSUE THREAD

**Issue by nic2013** [lejianwen/rustdesk-api#239]
如果vps重装系统后重新编排了Docker，就会生成一个新的key。
我停止了Docker服务，直接修改挂载出来的 /data/id_ed25519.pub  key文件会导致Docker无法启动。
要不然换了vps，又要重新编译客户端。怎么解决这个问题？谢谢！

**Comment by IamTaoChen** [comment]
试试 
```yaml
services:
  rustdesk:
    environment:
      KEY_PRIV: /run/secrets/key_priv
      KEY_PUB: /run/secrets/key_pub
    secrets:
      - key_pub
      - key_priv
secrets:
  key_pub:
    file: ./secrets/pub.key
  key_priv:
    file: ./secrets/praivte.key
```
