### ISSUE TITLE
dial tcp 127.0.0.1:21115: connect: connection refused, dial tcp 127.0.0.1:21115: connect: connection refused

### ISSUE THREAD

**Issue by ahmaddxb** [lejianwen/rustdesk-api#241]
I get this error in WebUI on ServerCmdTips page

```
dial tcp 127.0.0.1:21115: connect: connection refused
dial tcp 127.0.0.1:21115: connect: connection refused
```

  ```
networks:
    rustdesk-net:
      external: false
  services:
    hbbs:
      container_name: hbbs
      ports:
        - 21115:21115
        - 21116:21116
        - 21116:21116/udp
        - 21118:21118
      image: rustdesk/rustdesk-server
      command: hbbs -r serverip:21117 -k 123456789
      volumes:
        - $APPDATADIR/rustdesk/server:/root
      networks:
        - rustdesk-net
      depends_on:
        - hbbr
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 64M
    hbbr:
      container_name: hbbr
      ports:
        - 21117:21117 # 自定义 hbbr 映射端口
        - 21119:21119 # web client
      image: rustdesk/rustdesk-server
      command: hbbr -k 123456789
      volumes:
        - $APPDATADIR/rustdesk/server:/root
      networks:
        - rustdesk-net
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 64M
    rustdesk-api:
      container_name: rustdesk-api
      environment:
        - TZ=$TZ
        - RUSTDESK_API_RUSTDESK_ID_SERVER=serverip:21116
        - RUSTDESK_API_RUSTDESK_RELAY_SERVER=serverip:21117
        - RUSTDESK_API_RUSTDESK_API_SERVER=http://serverip:21114
        #- RUSTDESK_API_RUSTDESK_KEY=<key>
      ports:
        - 21114:21114
      image: lejianwen/rustdesk-api
      volumes:
        - $APPDATADIR/rustdesk/api:/app/data #将数据库挂载出来方便备份
        - $APPDATADIR/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
      networks:
        - rustdesk-net
      restart: unless-stopped
      depends_on:
        - hbbs
        - hbbr
```
