### ISSUE TITLE
LDAP or LDAPS Integration

### ISSUE THREAD

**Issue by iippam** [lejianwen/rustdesk-api#247]
Hi, 
I really appreciate about this project; it's really had much feature that what really helpful for me.
I am trying to use LDAP/s for the login, but still doesn't work with LDAP users, only local user can used. 😥
If you enter the wrong password 3 times, then CAPTCHA will be showing, that it's really difficult to understand/read the CAPTCHA, so I need to wait 5 or 10 minutes to login without CAPTCHA or restart the container.

For your information, my current server is isolated from Internet, so I need to export and import the docker images from Online Devices to this server.

Also when opening the webclient2 is just loading the Rustdesk logo, but my priority is to enable the LDAP/s.

![Image](https://github.com/user-attachments/assets/bba6a8a4-497b-404f-b86f-754e71fe4a29)

Here is my docker-compose.yml
```dockerfile
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-api:full-s6
     environment:
       - RELAY=192.168.100.50:21117
       - ENCRYPTED_ONLY=1
       - TZ=Asia/Jakarta
       - RUSTDESK_API_RUSTDESK_ID_SERVER=192.168.100.50:21116 #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=192.168.100.50:21117 #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://192.168.100.50:21114 #21114
     #  - RUSTDESK_API_ADMIN_HELLO_FILE=./conf/admin/hello.html
     volumes:
       - ./data/rustdesk/server:/data  #将server的key挂载出来
       - ./data/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
       - ./data/rustdesk/api:/app/data #将数据库挂载
       - ./conf:/app/conf # config
      # - ./resources:/app/resources # 静态资源
     networks:
       - rustdesk-net
     restart: unless-stopped
``` 

and below is my config.yaml
```go
lang: "en"
app:
  web-client: 1  # 1:启用 0:禁用
  register: false #是否开启注册
  show-swagger: 0 # 1:启用 0:禁用
  token-expire: 168h
  web-sso: true #web auth sso
  disable-pwd-login: false #禁用密码登录
admin:
  title: "RustDesk Api Dashboard"
  hello-file: "./conf/admin/hello.html"  #优先使用file
  hello: ""
gin:
  api-addr: "0.0.0.0:21114"
  mode: "release" #release,debug,test
  resources-path: 'resources'  #对外静态文件目录
  trust-proxy: ""
gorm:
  type: "sqlite"
  max-idle-conns: 10
  max-open-conns: 100
mysql:
  username: ""
  password: ""
  addr: ""
  dbname: ""
rustdesk:
  id-server: "192.168.100.50:21116"
  relay-server: "192.168.100.50:21117"
  api-server: "http://127.0.0.1:21114"
  key: ""
  key-file: "./data/rustdesk/server/id_ed25519.pub"
  personal: 1
  webclient-magic-queryonline: 0
  ws-host: ""  #eg: wss://192.168.1.3:4443
logger:
  path: "./runtime/log.txt"
  level: "trace" #trace,debug,info,warn,error,fatal
  report-caller: true
proxy:
  enable: false
  host: "http://127.0.0.1:1080"
jwt:
  key: ""
  expire-duration: 168h
ldap:
  enable: false
  url: "ldap://192.168.100.45:389"
  tls-ca-file: ""
  tls-verify: false
  base-dn: "dc=dev-local,dc=net"
  bind-dn: "cn=XXX90002,OU=Functions,OU=XXX,OU=ID,OU=Locations,DC=dev-local,DC=net"
  bind-password: "b1nd-p@ssw0rd"

  user:
    base-dn: "ou=Locations,dc=dev-local,dc=net"
    enable-attr: ""       #The attribute name of the user for enabling, in AD it is "userAccountControl", empty means no enable attribute, all users are enabled
    enable-attr-value: "" # The value of the enable attribute when the user is enabled. If you are using AD, just set random value, it will be ignored.
    filter: "(cn=*)"
    username: "sAMAccountName"       # The attribute name of the user for usernamem if you are using AD, it should be "sAMAccountName"
    email: "mail"
    first-name: "givenName"
    last-name: "sn"
    sync: true         # If true, the user will be synchronized to the database when the user logs in. If false, the user will be synchronized to the database when the user be created.
    admin-group: "cn=sysops,dc=dev-local,dc=net" # The group name of the admin group, if the user is in this group, the user will be an admin.



``` 

Below is my folder structure:
```shell
/rustdesk_project# tree
.
├── conf
│   ├── admin
│   │   └── hello.html
│   ├── config.yaml
│   └── data
├── data
│   └── rustdesk
│       ├── api
│       │   └── rustdeskapi.db
│       └── server
│           ├── db_v2.sqlite3
│           ├── db_v2.sqlite3-shm
│           ├── db_v2.sqlite3-wal
│           ├── hello.html
│           ├── id_ed25519
│           └── id_ed25519.pub
├── docker-compose.yml
├── runtime
└── rustdesk-api-full-s6 (1).tar

9 directories, 11 files

``` 
I am using a quiet similar LDAPs base and bind dn for other apps (eq: Nextcloud), and it's working.

Please help to check my current configuration, might be any missing or miss-configuration there.

Thank you very much. 😊😊

**Comment by lejianwen** [comment]
About LDAP , i need help. 
@IamTaoChen Can you help me ? Thank you


> Also when opening the webclient2 is just loading the Rustdesk logo

Can you successfully  load https://rustdesk.com/web/ ?

> CAPTCHA

Maybe I should add a switch

**Comment by iippam** [comment]
> About LDAP , i need help. [@IamTaoChen](https://github.com/IamTaoChen) Can you help me ? Thank you

> > Also when opening the webclient2 is just loading the Rustdesk logo
> 
> Can you successfully load https://rustdesk.com/web/ ?

> > CAPTCHA
> 
> Maybe I should add a switch

I can't load the https://rustdesk.com/web/ from this server, because this server not connected to internet (isolated network). 😥, internet access is prohibited for this env.
If there are any options to make webclient2 are working on local environment without any internet access required?

and it might be a good option to switch the capctha. 💡

Thank you for your reply. 😊

**Comment by IamTaoChen** [comment]
> bind-dn: "cn=XXX90002,OU=Functions,OU=XXX,OU=ID,OU=Locations,DC=dev-local,DC=net"

Are you using AD? 
1. Try `User Principal Name ` here
2. And does the AD allow 389 to connect?

**Comment by iippam** [comment]
> > bind-dn: "cn=XXX90002,OU=Functions,OU=XXX,OU=ID,OU=Locations,DC=dev-local,DC=net"
> 
> Are you using AD? 
> 1. Try `User Principal Name ` here
> 2. And does the AD allow 389 to connect?
> 
> Any log information is helpful.

Yes, I am using AD, 
LDAP port 389 and LDAPS port 636 both are open, also reachable from this rustdesk server api.

My Portainer and Nextcloud are connected to AD for the login function.

**Comment by iippam** [comment]
> > > > bind-dn: "cn=XXX90002,OU=Functions,OU=XXX,OU=ID,OU=Locations,DC=dev-local,DC=net"
> > > 
> > > 
> > > Are you using AD?
> > > 
> > > 1. Try `User Principal Name ` here
> > > 2. And does the AD allow 389 to connect?
> > > 
> > > Any log information is helpful.
> > 
> > 
> > Yes, I am using AD, LDAP port 389 and LDAPS port 636 both are open, also reachable from this rustdesk server api.
> > My Portainer and Nextcloud are connected to AD for the login function.
> 
> When you try to login, is there any error message printed on the console?

Logs:
```dockerfile
[2025-05-20 22:22:15] [WARN] Login Fail: UsernameOrPasswordError 192.168.100.118 192.168.100.118 (/home/runner/work/rustdesk-api/rustdesk-api/http/controller/admin/login.go:186 github.com/lejianwen/rustdesk-api/v2/http/controller/admin.(*Login).Login)
``` 

config.yaml using `User Principal Name `
```dockerfile
ldap:
  enable: false
  url: "ldap://192.168.100.45:389"
  tls-ca-file: ""
  tls-verify: false
  base-dn: "dc=dev-local,dc=net"
  bind-dn: "userPrincipalName=XXX90003@dev-local.net,OU=Functions,OU=XXX,OU=ID,OU=Locations,DC=dev-local,DC=net"
  bind-password: "123456!*"

  user:
    base-dn: "ou=Locations,dc=dev-local,dc=net"
    enable-attr: ""       #The attribute name of the user for enabling, in AD it is "userAccountControl", empty means no enable attribute, all users are enabled
    enable-attr-value: "" # The value of the enable attribute when the user is enabled. If you are using AD, just set random value, it will be ignored.
    filter: "(cn=*)"
    username: "sAMAccountName"       # The attribute name of the user for usernamem if you are using AD, it should be "sAMAccountName"
    email: "mail"
    first-name: "givenName"
    last-name: "sn"
    sync: true         # If true, the user will be synchronized to the database when the user logs in. If false, the user will be synchronized to the database when the user be created.
    admin-group: "cn=sysops,dc=dev-local,dc=net" # The group name of the admin group, if the user is in this group, the user will be an admin.
```

**Comment by IamTaoChen** [comment]
>  bind-dn: "cn=XXX90002,OU=Functions,OU=XXX,OU=ID,OU=Locations,DC=dev-local,DC=net"
```yaml
bind-dn: "userPrincipalName=XXX90003@dev-local.net"
```


I test with my AD, it works.

```yaml
ldap:
  enable: true
  url: "ldap://ad.ds.demo.com:389"
  tls: false
  tls-verify: false
  base-dn: "ou=Demo,dc=ds,dc=demo,dc=com"
  bind-dn: "reader@ds.demo.com"
  bind-password: "xxxx"
  user:
    base-dn: "ou=Users,ou=Demo,dc=ds,dc=demo,dc=com"
    enable-attr: ""       #The attribute name of the user for enabling, in AD it is "userAccountControl", empty means no enable attribute, all users are enabled
    enable-attr-value: "" # The value of the enable attribute when the user is enabled. If you are using AD, just set random value, it will be ignored. 
    filter: "(cn=*)"
    username: "sAMAccountName"       # The attribute name of the user for usernamem if you are using AD, it should be "sAMAccountName"
    email: "mail"
    first-name: "givenName"
    last-name: "sn"
    sync: false         # If true, the user will be synchronized to the database when the user logs in. If false, the user will be synchronized to the database when the user be created.
    admin-group: "cn=admins,ou=groups,ou=Demo,dc=ds,dc=demo,dc=com" # The group name of the admin group, if the user is in this group, the user will be an admin.
    
```
