### ISSUE TITLE
控制台web页面账号密码是多少哪里看 ？按文档提示未发现

### ISSUE THREAD

**Issue by shen-lan** [lejianwen/rustdesk-api#294]
大佬你好。按文档提示去找日志密码  并未发现 
1、docker 配置

```
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     container_name: "rustdesk-server"
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RELAY=127.0.0.1:21117
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=N #是否必须登录
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=127.0.0.1:21116 #21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=127.0.0.1:21117 #21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://127.0.0.1:21114 #21114
       - RUSTDESK_API_RUSTDESK_KEY_FILE=/data/id_ed25519.pub
      #  - RUSTDESK_API_JWT_KEY=d^ngdPJ$Trn8TeX # jwt key
     volumes:
       - ./server:/data  #将server的key挂载出来
       - ./api:/app/data #将数据库挂载
     networks:
       - rustdesk-net
     restart: unless-stopped

```

2、日志

```
root@iStoreOS:/mnt/nvme0n1p4/rustdesk# docker logs rustdesk-server | grep admin
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service key-secret: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service key-secret successfully started
s6-rc: info: service hbbr: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service hbbr successfully started
s6-rc: info: service hbbs: starting
s6-rc: info: service hbbs successfully started
s6-rc: info: service api: starting
s6-rc: info: service api successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2025/06/18 16:45:02 114 0.0.0.0:21114
[2025-06-18 16:49:09] [WARN] Login Fail: UsernameOrPasswordError 192.168.64.1 192.168.64.1 (/home/runner/work/rustdesk-api/rustdesk-api/http/controller/admin/login.go:69 github.com/lejianwen/rustdesk-api/v2/http/controller/admin.(*Login).Login)
root@iStoreOS:/mnt/nvme0n1p4/rustdesk#
```
