### ISSUE TITLE
Relay-server running on different server

### ISSUE THREAD

**Issue by iippam** [lejianwen/rustdesk-api#301]
Hi,

I am trying to have Rustdesk Server and API Server running on the same VM,
and Relay server running on a different VM.
I also change the config.yaml on rustdesk "relay-server:" section with 192.168.11.200:21117

but I am facing a problem on ServerCMD,
Relay status not available.

![Image](https://github.com/user-attachments/assets/29349684-fe4b-423b-b462-eea9397a6288)

Everything running smoothly and OK when Server, Relay and API Server running on same VM.

Do you have idea for this?
What I am missing here?

Thank you.

**Comment by iippam** [comment]
> This function is designed for that they are on the same server. But there may be a solution by creating a tunnel?


If I only change the settings from ServerCmd, yes a new relay server will respons, I checked from the logs.
RELAY_SERVERS AND Turn ON the ALWAYS_USE_RELAY.
Every connection will directly to the Relay Server.

![Image](https://github.com/user-attachments/assets/02091fb7-ccb0-4278-9e27-4aa960354257)

The Relay status will available if I am set the config.yaml with 
```
admin:
  title: "RustDesk API Admin"
  hello-file: "./conf/admin/hello.html"  #优先使用file
  hello: ""
  # ID Server and Relay Server ports https://github.com/lejianwen/rustdesk-api/issues/257
  id-server-port: 21116  # ID Server port (for server cmd)
  relay-server-port: 21117 # ID Server port (for server cmd)
``` 

in my understanding, if the Rustdesk Server down or not reachable, it will goes to the Relay server?
So, I am trying to make the server not it the same host.

I am not familiar with creating a tunnel. 😥

Thank you.
