### ISSUE TITLE
github oauth 登录页面异常

### ISSUE THREAD

**Issue by wxyShine** [lejianwen/rustdesk-api#302]
首页点击GitHub登录 先出现图一 然后自动图二 点击close 自动关闭网页  再次输入网址打开就登录成功了！  是我哪里配置的有问题吗？

![Image](https://github.com/user-attachments/assets/74312b5f-e94e-41bf-acd7-8883e3a9f13b)

![Image](https://github.com/user-attachments/assets/569aefda-9b77-48e3-889d-9e33ce623584)

附上docker compose文件
```yml
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     container_name: rustdesk-server-api
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RELAY=<relay_server[:port]>
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=N
       - TZ=Asia/Shanghai
       - RUSTDESK_API_RUSTDESK_ID_SERVER=<id_server[:21116]>
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<relay_server[:21117]>
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://<api_server[:21114]>
       - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
       - RUSTDESK_API_JWT_KEY=xxxxxx # jwt key
     volumes:
       - ./server:/data
       - ./api:/app/data #将数据库挂载
     networks:
       - rustdesk-net
     restart: unless-stopped
```
