### ISSUE TITLE
Web端远程控制无法连接中继服务器？

### ISSUE THREAD

**Issue by Smianao** [lejianwen/rustdesk-api#7]
![QQ截图20241010101742](https://github.com/user-attachments/assets/c04745f8-978c-4312-a124-ffd17657529d)
如题，登录账号后，服务器和key信息也自动识别到了，但是网页端远控，就会提示这个，请问大佬是怎么回事？？本地和服务器环境都测试了！

**Comment by lejianwen** [comment]
是不是21119端口没开？
可以看下怎么配置的吗？

**Comment by Smianao** [comment]
我是用docker compose部署的 在你配置文件上简单修改了下 服务器端口放行没问题啊 TCP 21114-21119  UDP 21116

**Comment by lejianwen** [comment]
Compose配置文件看一下？

**Comment by Smianao** [comment]
networks:
  rustdesk-net:
    external: false
services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116 # 自定义 hbbs 映射端口
      - 21116:21116/udp # 自定义 hbbs 映射端口
      - 21118:21118 # web client
      - 21119:21119 # web client
    image: rustdesk/rustdesk-server
    command: hbbs -r rustdesk.smianao.com:21117 -k andy19860219 # 填入个人域名或 IP + hbbr 暴露端口
    volumes:
      - /data/rustdesk/hbbs:/root # 自定义挂载目录
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117 # 自定义 hbbr 映射端口
    image: rustdesk/rustdesk-server
    command: hbbr -k andy19860219
    #command: hbbr
    volumes:
      - /data/rustdesk/hbbr:/root # 自定义挂载目录
    networks:
      - rustdesk-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
  rustdesk-api:
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk.smianao.com:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk.smianao.com:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://rustdesk.smianao.com:21114
      - RUSTDESK_API_RUSTDESK_KEY=andy19860219
    ports:
      - 21114:21114
    image: lejianwen/rustdesk-api
    volumes:
      - /data/rustdesk/api:/app/data #将数据库挂载出来方便备份
    networks:
      - rustdesk-net
    restart: unless-stopped

**Comment by Smianao** [comment]
请问是什么原因？？别的功能都正常 就这个web客户端不能用

**Comment by lejianwen** [comment]
我看是这个连不上ws://<youserver>:21119/

**Comment by Smianao** [comment]
请问老师，有处理的方法吗？？

**Comment by lejianwen** [comment]
我的问题，21119是hbbr要开放的端口

```
     hbbr:
       container_name: hbbr
       ports:
         - 21117:21117 # 自定义 hbbr 映射端口
         - 21119:21119 # web client
```

**Comment by lejianwen** [comment]
改一下compose的配置应该就可以了

**Comment by Smianao** [comment]
具体怎么改？？抱歉 ，我是小白 哈哈

**Comment by lejianwen** [comment]
你的compose中，原来是
```
   services:
     hbbs:
       container_name: hbbs
       ports:
         - 21115:21115
         - 21116:21116 # 自定义 hbbs 映射端口
         - 21116:21116/udp # 自定义 hbbs 映射端口
         - 21118:21118 # web client
         - 21119:21119 # web client 这行删除
       image: rustdesk/rustdesk-server
     ...
```
将这个` - 21119:21119 # web client`移动到
```
     hbbr:
       container_name: hbbr
       ports:
         - 21117:21117 # 自定义 hbbr 映射端口
         - 21119:21119 # web client  放到这
      ...
```
