### ISSUE TITLE
webclient连接一直提示失败

### ISSUE THREAD

**Issue by 1229984599** [lejianwen/rustdesk-api#72]
麻烦大佬空了帮我看看呀，以下是报错信息，目前21114-21119所有端口都已经开放，除了webclient外其他都能够正常使用。
![image](https://github.com/user-attachments/assets/9c2b91b5-78c7-499c-b6c1-750866fc0222)
我的`docker-compose.yaml`配置如下：
```
networks:
  rustdesk-net:
    external: false
services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: iamtaochen/rustdesk-server:stcp
    environment:
      - RELAY=desk.***.top
      - ENCRYPTED_ONLY=1
      - KEY=nTimjyWnqH9l*******
    volumes:
      - ./data:/data
      - ./hbbr/run:/etc/s6-overlay/s6-rc.d/hbbr/run
      - ./hbbs/run:/etc/s6-overlay/s6-rc.d/hbbs/run
    restart: unless-stopped
  rustdesk-api:
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=desk.***.top:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=desk.***.top:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=https://desk.***.top
      - RUSTDESK_API_RUSTDESK_KEY=nTimjyWnqH9l0*******
    ports:
      - 21114:21114
    image: lejianwen/rustdesk-api:latest
    volumes:
      - /data/rustdesk:/app/data
    networks:
      - rustdesk-net
    restart: unless-stopped
```
在我的宝塔设置的反向代理如下（这部分代码几乎抄的issue中的）：
```
# 如果反代网站访问异常且这里已经配置了内容，请优先排查此处的配置是否正确

upstream rustdesk-api {
    server 127.0.0.1:21114;
}

upstream rustdesk-id {
    server 127.0.0.1:21118;
}

upstream rustdesk-relay {
    server 127.0.0.1:21119;
}
server {
    listen 80;
    
    listen 443 ssl http2 ;
    listen [::]:80;
    
    listen [::]:443 ssl http2 ;
    
    server_name desk.******.top;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/desk.******.top;

    #CERT-APPLY-CHECK--START
    # 用于SSL证书申请时的文件验证相关配置 -- 请勿删除
    include /www/server/panel/vhost/nginx/well-known/desk.***.top.conf;
    #CERT-APPLY-CHECK--END

    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则

    #PROXY-CONF-START
    location ^~ / {
      proxy_pass http://127.0.0.1:21114;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Real-Port $remote_port;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header REMOTE-HOST $remote_addr;
      proxy_connect_timeout 60s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade; 
    }

location /ws/id {
            proxy_pass http://rustdesk-id;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /ws/relay {
            proxy_pass http://rustdesk-relay;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
}
```
